[en]
  title = "Helio's Website"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[es]
  title = "Version español"
  languageName = "Español"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/es"
  

