[[main]]
  identifier = "posts"
  name = "ğŸ“†Posts"
  url = "posts"
  weight = 1
  
[[main]]
  identifier = "publication"
  name = "ğŸ“°Publicaciones"
  url = "publication"
  weight = 2

[[main]]
  identifier = "programacion"
  name = "ğŸ’»ProgramaciÃ³n"
  url = "programacion"
  weight = 3
  
[[main]]
  identifier = "musica"
  name = "ğŸ§MÃºsica"
  url = "musica"
  weight = 4  

[[main]]
  identifier = "carpinteria"
  name = "ğŸ“CarpinterÃ­a"
  url = "carpinteria"
  weight = 5

[[main]]
  identifier = "archive"
  name = "ğŸ“…Archivo"
  url = "archive"
  weight = 6
  
[[main]]
  identifier = "about"
  name = "Acerca de"
  url = "about"
  weight = 7